---
- hosts: ggr
  become: yes
  vars:
    grid_router_version: 1.5.0
    grid_router_path: "{{ ansible_env.HOME }}/grid-router"
    grid_router_qouta_path: "{{ ansible_env.HOME }}/grid-router/quota"
    grid_router_port: 4444

    grid_router_regions:
        - name: "cluster 1"
          hosts:
          - name: 35.196.216.150
            port: 4444
            browser_count: 4
        - name: "cluster 2"
            hosts:
              - name: 198.199.69.245
                port: 4444
                browser_count: 4

    grid_router_browsers:
        - name: "chrome"
          defaultVersion: "62.0"
          versions:
            - "62.0"
            - "63.0"
  roles:
    - gridrouter-docker

- hosts: selenoid-nodes
  become: yes
  vars:
    selenoid_version: 1.5.2
    selenoid_cm_version: 1.4.0
    selenoid_docker_api_version: 1.35
    selenoid_limit: 4
    selenoid_tmpfs: 128
    selenoid_config_dir: "{{ ansible_env.HOME }}/selenoid"
    selenoid_listen_port: 4444
    selenoid_browsers_last_versions: 3
    selenoid_browsers:
      - chrome
  roles:
    - selenoid-ansible
